# Generated by Django 2.2.5 on 2020-05-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('publisher', models.CharField(max_length=50)),
                ('rep_img_url', models.CharField(blank=True, max_length=400)),
                ('published_at', models.DateTimeField()),
                ('body', models.TextField()),
                ('hashtag', models.TextField()),
            ],
        ),
    ]
