# Generated by Django 3.0.6 on 2020-05-23 18:29

import BlogApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_auto_20200523_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='hashtag',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='blog',
            name='rep_img',
            field=models.ImageField(blank=True, default=None, upload_to=BlogApp.models.date_upload_to),
        ),
    ]
